# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69b5df4c98d3e445eaaf8a694030d9ca5a01e6e3a0b9bdfd981fe6cd2855b2a9e53f2a17f725e6214fa853bcac3d31d0dc3d8700dc727f5957e43cb75b7155d6

test:
  secret_key_base: b7ce1ddcd2eb816933cde737b2690be31afa7efe9e0fd0a5f9253fb70e73769c97eed98ba30f306a8ef995cf92a595e3d19bddb725e42da62e2a9eb9c6230ca4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
